---
title: "Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ModernBayes)
library(caret)
library(randtoolbox)
```

## Loading example data 
The example data is downloaded from the [UCI Machine learning repository](https://archive.ics.uci.edu/ml/datasets/breast+cancer+wisconsin+(diagnostic)).
```{r}
breastCancerDataset <- read.csv("breast_cancer_data.csv")
X = data.matrix(breastCancerDataset[, 3:32]) # raw features
y = as.double(data.matrix(breastCancerDataset['diagnosis'] == 'M')) # labels
```

## Generate beta samples with MCMC
```{r}
beta_samples = MCMC.beta.generate(LogisticModel, GaussianLogPrior, LogisticLogLik, logPosteriorFunction, X, y)
MCMC.X = beta_samples$X
MCMC.betas = beta_samples$sample_stationary
```

## Prediction of logistic regression using beta samples returned by MCMC
```{r}
y_pred = Logistic.prediction(MCMC.X, MCMC.betas, y)
confusionMatrix(data=y_pred, reference = factor(y))
```

## Generate beta samples with SVGD
```{r}
beta_samples = SVGD.beta.generate(LogisticModel, GaussianLogPrior, LogisticLogLik, X, y)
SVGD.X = beta_samples$X
SVGD.betas = beta_samples$beta_samples
```

## Prediction of logistic regression using beta samples returned by SVGD
```{r}
y_pred = Logistic.prediction(SVGD.X, SVGD.betas, y)
confusionMatrix(data=y_pred, reference = factor(y))
```

## Run time comparison 
```{r}
system.time(MCMC.beta.generate(LogisticModel, GaussianLogPrior, LogisticLogLik, logPosteriorFunction, X, y))
system.time(SVGD.beta.generate(LogisticModel, GaussianLogPrior, LogisticLogLik, X, y))
```



